### ISSUE TITLE
Checkpointing and resuming

### ISSUE THREAD

**Issue by etetteh** [optuna/optuna#2638] opened 2021-04-30 02:12 UTC
I want to checkpoint and resume training (hyperparameter search), but that is not happening.

```
study_name = "baseline-study" 
storage_name = "sqlite:///{}.db".format(study_name)

sampler = optuna.samplers.TPESampler(seed=seed)    
study = optuna.create_study(
                sampler=sampler,
                pruner=optuna.pruners.MedianPruner(n_startup_trials=3, n_warmup_steps=5, interval_steps=3),
                direction='maximize',
                study_name=study_name,
                storage=storage_name,
                load_if_exists=True) 

study.optimize(func=objective, n_trials=5, gc_after_trial=True)
```

The code is to perform t trials. At the 4th training, I intentionally halted the execution and ran the code again, I expected the code to run for only  1 trial, to complete the total trials of 5. However, the code executed more than the remaining 1 trial.

Is there a fix to this issue?

**Comment by nzw0301** [comment] 2021-04-30 08:45
Hi, @etetteh, thank you for asking your question! 

I think this is expected behaviour because `n_trials` is the number of *forthcoming* trials to perform, not the total number of trials in the study.

Thus, I suggest setting the maximum number of trials before optimisation as follows:

```python
import optuna

study_name = "baseline-study" 
storage_name = "sqlite:///{}.db".format(study_name)
seed = 7
max_num_trials = 5

sampler = optuna.samplers.TPESampler(seed=seed)    
study = optuna.create_study(
                sampler=sampler,
                pruner=optuna.pruners.MedianPruner(n_startup_trials=3, n_warmup_steps=5, interval_steps=3),
                direction='maximize',
                study_name=study_name,
                storage=storage_name,
                load_if_exists=True) 

def objective(trial):
    return 1

num_rest_trials = max_num_trials - len(study.get_trials())
study.optimize(func=objective, n_trials=num_rest_trials, gc_after_trial=True)
```

Otherwise, we can use the custom callback that is available in [this example](https://github.com/optuna/optuna/blob/master/examples/max_trials_callback.py).

**Comment by etetteh** [comment] 2021-05-01 00:11
Unfortunately, none of the suggestions helped.
What I want is to be able to checkpoint the trial and number of epochs of my training, so that I can resume training after an interruption.

**Comment by not522** [comment] 2021-05-02 03:04
Maybe this example will help you. It is an example of PyTorch, but you can code it in other frameworks. https://github.com/optuna/optuna/blob/master/examples/pytorch/pytorch_checkpoint.py

**Comment by etetteh** [comment] 2021-05-05 04:22
> Hi @etetteh, thank you for asking your question!
> 
> I think this is expected behaviour because `n_trials` is the number of _forthcoming_ trials to perform, not the total number of trials in the study.
> 
> Thus, I suggest setting the maximum number of trials before optimisation as follows:
> 
> ```python
> import optuna
> 
> study_name = "baseline-study" 
> storage_name = "sqlite:///{}.db".format(study_name)
> seed = 7
> max_num_trials = 5
> 
> sampler = optuna.samplers.TPESampler(seed=seed)    
> study = optuna.create_study(
>                 sampler=sampler,
>                 pruner=optuna.pruners.MedianPruner(n_startup_trials=3, n_warmup_steps=5, interval_steps=3),
>                 direction='maximize',
>                 study_name=study_name,
>                 storage=storage_name,
>                 load_if_exists=True) 
> 
> def objective(trial):
>     return 1
> 
> num_rest_trials = max_num_trials - len(study.get_trials())
> study.optimize(func=objective, n_trials=num_rest_trials, gc_after_trial=True)
> ```
> 
> Otherwise, we can use the custom callback that is available in [this example](https://github.com/optuna/optuna/blob/master/examples/max_trials_callback.py).

I combined the code above with your suggestion (https://github.com/optuna/optuna/issues/2638#issuecomment-830731905) and my problem was resolved. The suggestion alone wasn't a fix, but the combination worked

**Comment by hvy** [comment] 2021-05-17 05:54
Seems like this issue has been resolved, let me close it. 

For the record, the example has been moved to a new repository and https://github.com/optuna/optuna-examples/blob/main/pytorch/pytorch_checkpoint.py and starting from next 2.8.0, we now have a dedicated callback class for these types of stop conditions https://github.com/optuna/optuna/pull/2612.

**Closed by hvy** 2021-05-17 05:54 UTC
Labels: bug
