### ISSUE TITLE
Optimization is very slow after first couple of Trials

### ISSUE THREAD

**Issue by patrickpetre823** [optuna/optuna#3304] opened 2022-02-09 11:09 UTC
### Environment

- Optuna version:  - Not sure on this one but it was last version where n_jobs=-1 was working
- Python version: 3.8.8 64-bit
- OS: Windows 10
- (Optional) Other libraries and their versions:  torch 1.9.1

Currently my Optimization is still running and I dont want to stop it so I cant give exact output

### Question

In the first 3 hours of my optimization usually about 10 Trials are done. After that it tkes about 5-7 hours for one more Trial and then another 5-7 hours for the next. I let my optimization run with minimal Epoch number and tracked running time of different parameters and got rid of my biggest models as I thought these "big" architectures lead to these long running times, but still nothing changed. I am asking here since I didnt get any reply anywhere else. 

I run my optimization on a Intel Xeon Gold 6136 and since I started running it with n_jobs = -1. It starts much much faster (Before, each Trials would take a couple of hours). 

Current optimization started yesterday at 13:49 and up until 22:11, so in less then 10 hours a total of 24 Trials finished. Since then only 3 more Trials finished and it is now 12:00 the next day. So it took 10 Hours for 3 Trials.

### Error messages, stack traces, or logs

```shell
```

### Steps to reproduce

No clue how to reproduce

1.
2.
3.
```python
# python code
```

**Comment by patrickpetre823** [comment] 2022-02-09 16:06
But if my training code, objective function would cause this, every trial would be slow. I benchmarked my Paramters for 400 Trials. Each Trial only 10 Epochs. Range went from 10 seconds ( smallest models) to 140 seconds (biggest models). So I limited my Search space drastically to only a smal model

**Comment by nzw0301** [comment] 2022-02-09 16:15
could you share minimal reproducible codes with us?

**Comment by nzw0301** [comment] 2022-02-17 08:01
We could not leave comments anymore because it is really hard to investigate this issue without reproducible code. Let me close this issue once. However, please feel free to reopen this issue with reproducible code.

**Closed by nzw0301** 2022-02-17 08:01 UTC
Labels: question
