### ISSUE TITLE
Doesnt work with MySql or PostgreSql

### ISSUE THREAD

**Issue by rafaeldelrey** [optuna/optuna#642] opened 2019-10-26 16:01 UTC
While using Optuna with Keras (from Tensorflow 1.13 or 1.14), I cannot make it work with MySql or Postgre.  It seems Optuna is passing a numpy.float32 for sqlalchemy, which is causing problems (I have tried pymysql or mysqldb connectors, as well as some connectors for pg).

it seems on trial.py, line 378, there should be some handling of value param being passed to sqlalchemy.

self.storage.set_trial_value(self._trial_id, value)

This is the error I m getting:
AttributeError: 'numpy.float32' object has no attribute 'translate'

Since this function is called from inside a keras callback, there is no easy way for the Optuna user to change this, afaik.

**Comment by toshihikoyanase** [comment] 2019-10-28 06:40
Thank you for your feedback.
I think I can reproduce your problem using PostgreSQL as follows:

Library
- optuna==0.17.1
- tensorflow==1.15.0

Shell script:
```shell
$ STORAGE_URL=postgres://...
$ STUDY_NAME=`optuna create-study --storage $STORAGE_URL --direction=maximize`
$ optuna study optimize examples/pruning/tfkeras_integration.py objective --storage=$STORAGE_URL --study=$STUDY_NAME
```

Output:
```
19-10-28 15:05:14,256] Setting status of trial#17 as TrialState.FAIL because of the following error: StorageInternalError('An exception is raised during the commit. This typically happens due to invalid data in the commit, e.g. exceeding max length. (The actual exception is as follows: ProgrammingError("(psycopg2.ProgrammingError) can\'t adapt type \'numpy.float32\'"))')
```

> Since this function is called from inside a keras callback, there is no easy way for the Optuna user to change this, afaik.

As you mentioned, `TFKerasPruningCallback` reports raw scores returned by TFKeras to `Trial` [here](https://github.com/pfnet/optuna/blob/master/optuna/integration/tfkeras.py#L62). But, I think the values should be cast to `float` like the returned value of objective function [here](https://github.com/pfnet/optuna/blob/master/optuna/study.py#L531).

**Comment by toshihikoyanase** [comment] 2020-01-17 04:59
Closing the issue since #644 resolved it.
Please feel free to reopen it or create a new issue if you have any questions or comments.

**Closed by toshihikoyanase** 2020-01-17 04:59 UTC
Labels: bug
