### ISSUE TITLE
LightGBMTunerCV never begins trials

### ISSUE THREAD

**Issue by rabyj** [optuna/optuna#3960] opened 2022-09-02 21:18 UTC
### Expected behavior

I'm putting two problems together because they have the same input, just one version has a smaller input. I imagine they are related. This might be a LightGBM problem, and not optuna. The issue can be closed if that is the case.

Expected behavior : [ LightGBMTunerCV](https://github.com/optuna/optuna-examples/blob/main/lightgbm/lightgbm_tuner_cv.py) begins trials after LightGBM prints total bin number.

Observed behaviour:  LightGBMTunerCV.run() ends and exits the program without any trials or errors. Last prints are related to total bin size. Internal Training dataset not constructed.

After reducing the total data from 1096 samples (~130 mb) to 542 samples, the problem **slightly** changes. (same data source/classes, still same number of samples for each class). I get a bit more prints indicating the training set was constructed, but then it stops similarly.

If the dataset is reduced even further, trials seem to start.

### Environment

- Optuna version: 3.0.0
- Python version: 3.8.10
- OS: Linux-5.15.0-46-generic-x86_64-with-glibc2.29 (Ubuntu 20.04.5 LTS)
- lightgbm : 3.3.2

### Error messages, stack traces, or logs

SITUATION 1
Logs with verbosity 4:
```
[I 2022-09-01 17:18:25,811] A new study created in memory with name: no-name-f7558179-1685-4799-a668-4d05bb21188a
[LightGBM] [Debug] Dataset::GetMultiBinFromAllFeatures: sparse rate 0.000000
[LightGBM] [Debug] init for col-wise cost 0.026579 seconds, init for row-wise cost 2.166356 seconds
[LightGBM] [Warning] Auto-choosing col-wise multi-threading, the overhead of testing was 4.252611 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 7731833
```

Full stack context before end.
```
__init__ (/home/local/USHERBROOKE/<user>/Projects/epilap/venv-epilap-pytorch/lib/python3.8/site-packages/lightgbm/basic.py:2610)
_make_n_folds (/home/local/USHERBROOKE/<user>/Projects/epilap/venv-epilap-pytorch/lib/python3.8/site-packages/lightgbm/engine.py:410)
cv (/home/local/USHERBROOKE/<user>/Projects/epilap/venv-epilap-pytorch/lib/python3.8/site-packages/lightgbm/engine.py:605)
__call__ (/home/local/USHERBROOKE/<user>/Projects/epilap/venv-epilap-pytorch/lib/python3.8/site-packages/optuna/integration/_lightgbm_tuner/optimize.py:319)
_run_trial (/home/local/USHERBROOKE/<user>/Projects/epilap/venv-epilap-pytorch/lib/python3.8/site-packages/optuna/study/_optimize.py:196)
_optimize_sequential (/home/local/USHERBROOKE/<user>/Projects/epilap/venv-epilap-pytorch/lib/python3.8/site-packages/optuna/study/_optimize.py:160)
_optimize (/home/local/USHERBROOKE/<user>/Projects/epilap/venv-epilap-pytorch/lib/python3.8/site-packages/optuna/study/_optimize.py:66)
optimize (/home/local/USHERBROOKE/<user>/Projects/epilap/venv-epilap-pytorch/lib/python3.8/site-packages/optuna/study/study.py:419)
_tune_params (/home/local/USHERBROOKE/<user>/Projects/epilap/venv-epilap-pytorch/lib/python3.8/site-packages/optuna/integration/_lightgbm_tuner/optimize.py:653)
tune_feature_fraction (/home/local/USHERBROOKE/<user>/Projects/epilap/venv-epilap-pytorch/lib/python3.8/site-packages/optuna/integration/_lightgbm_tuner/optimize.py:570)
run (/home/local/USHERBROOKE/<user>/Projects/epilap/venv-epilap-pytorch/lib/python3.8/site-packages/optuna/integration/_lightgbm_tuner/optimize.py:545)
tune_lbgm (/home/local/USHERBROOKE/<user>/Projects/sources/epi_ml/epi_ml/python/core/estimators.py:179)
main (/home/local/USHERBROOKE/<user>/Projects/sources/epi_ml/epi_ml/python/other_estimators.py:132)
<module> (/home/local/USHERBROOKE/<user>/Projects/sources/epi_ml/epi_ml/python/other_estimators.py:170)
_run_code (/usr/lib/python3.8/runpy.py:87)
_run_module_as_main (/usr/lib/python3.8/runpy.py:194)
```

SITUATION 2

Logs
```
[I 2022-09-02 16:09:15,257] A new study created in memory with name: no-name-73c934d6-7610-4800-bb86-995160cc7deb
[LightGBM] [Debug] Dataset::GetMultiBinFromAllFeatures: sparse rate 0.000000
[LightGBM] [Debug] init for col-wise cost 0.001908 seconds, init for row-wise cost 0.575387 seconds
[LightGBM] [Warning] Auto-choosing col-wise multi-threading, the overhead of testing was 1.194562 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 5493186
[LightGBM] [Info] Number of data points in the train set: 274, number of used features: 30321
[LightGBM] [Debug] Dataset::GetMultiBinFromAllFeatures: sparse rate 0.000000
[LightGBM] [Debug] init for col-wise cost 0.001943 seconds, init for row-wise cost 0.570320 seconds
[LightGBM] [Warning] Auto-choosing col-wise multi-threading, the overhead of testing was 1.317071 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 5493186
```

The full stack context before the end is the same in this case, no error traceback.

### Steps to reproduce

I was not able to create a minimal working example, since reducing the dataset size even more makes the problem disappear. 

Nonetheless, I pickled my input data (542 samples) to permit reproducing the problem with the following code (when the input is in the same folder):

```python
import lzma
import pathlib
import pickle

import optuna.integration.lightgbm as lgb

params = {
    "objective": "multiclass",
    "num_class": 4,
    "metric": "multi_logloss",
    "boosting_type": "dart",
    "seed": 42,
    "verbosity": 4,
}

with lzma.open(pathlib.Path(__file__).parent.resolve() / "input.pickle.xz", "rb") as f:
    input_data = pickle.load(f)

dtrain = input_data["dtrain"]
folds = input_data["folds"]

tuner = lgb.LightGBMTunerCV(
    params,
    dtrain,
    folds=folds,
    show_progress_bar=False,
)


tuner.run()
```
[Link to data](https://filedropper.com/d/s/tPWm52taJw0PYDnMvtIJ1sGeocJeaL)

### Additional context (optional)

essential part of my own code, which is not that far from [lightgbm_tuner_cv.py example](https://github.com/optuna/optuna-examples/blob/main/lightgbm/lightgbm_tuner_cv.py):
```python
    params = {
        "objective": "multiclass",
        "num_class": len(ea_handler.classes),
        "metric": "multi_logloss",
        "boosting_type": "dart",
        "seed": 42,
        "verbosity": 4,
    }

    total_data = ea_handler.create_total_data()
    folds = list(ea_handler.split(total_data))
    dtrain = lgb.Dataset(total_data.signals, label=total_data.encoded_label)

    tuner = lgb.LightGBMTunerCV(
        params,
        dtrain,
        folds=folds,
        show_progress_bar=False,
    )

    tuner.run()
```

- Data is multiclass
- lgbm dataset was created with:
  - `total_data.signals`: `ndarray[num_features, n_samples] (dtype=float32)`
  - `total_data.encoded_label`: `ndarray[n_samples] (dtype=int64)`
- `folds` is a list of the modified output of StratifiedKFold (repeated values for oversampling, but still same domain and format), so train and test idx. k=2 in kfold.
- `free_raw_data=False` changes nothing

([github](https://github.com/rabyj/epi_ml/commit/8960351c37e5fde20735f840413f899201d9b24f#diff-e370a91fe6e07469d65071226d2066a1c8b3883f87f7c534876d9fecd8429b01R137))

Codes goes up to [`_LIB.LGBM_BoosterCreate`](https://github.com/microsoft/LightGBM/blob/d78b6bc2fdf96c87e3cb61f2d497a962e3270c91/python-package/lightgbm/basic.py#L2730) through [`cvbooster = Booster(tparam, train_set)`](https://github.com/microsoft/LightGBM/blob/master/python-package/lightgbm/engine.py#L485) with what seems to be the correct training data. It just stops after printing some LightGBM info messages.

With reduced dataset (542 samples), code goes past `cvbooster = Booster(tparam, train_set)`) the first time, but it stops the second time it gets to `_LIB.LGBM_BoosterCreate` (creation of internal training set).

**Comment by nzw0301** [comment] 2022-09-03 05:44
Hi, thank you for providing the detailed info. I'm afraid that we could not download the compressed pickle file because the pickle is not secure as mentioned in https://docs.python.org/3/library/pickle.html. Could you create a code without loading the pickle file that you made for data?

**Comment by nzw0301** [comment] 2022-09-03 06:11
Note that I couldn't get a similar result to yours when I used `iris` dataset:

```python
import optuna.integration.lightgbm as lgb

from lightgbm import early_stopping
from lightgbm import log_evaluation
import sklearn.datasets
from sklearn.model_selection import KFold

data, target = sklearn.datasets.load_iris(return_X_y=True)
dtrain = lgb.Dataset(data, label=target)

params = {
    "objective": "multiclass",
    "num_class": len(set(target)),
    "metric": "multi_logloss",
    "boosting_type": "dart",
    "seed": 42,
    "verbosity": -1,
}

eval_results = {}

tuner = lgb.LightGBMTunerCV(
    params,
    dtrain,
    folds=KFold(n_splits=3),
    show_progress_bar=False,
)

tuner.run()
```

Related env info:
Lightgbm: 3.3.2
Optuna: 3.1.0.dev
Python: 3.9.13

**Comment by rabyj** [comment] 2022-09-06 17:09
> Hi, thank you for providing the detailed info. I'm afraid that we could not download the compressed pickle file because the pickle is not secure as mentioned in https://docs.python.org/3/library/pickle.html. Could you create a code without loading the pickle file that you made for data?

I cannot, as in do not know how, because the problem disappears with smaller datasets (like IRIS).

**Comment by rabyj** [comment] 2022-09-06 17:38
I've confirmed that Lightgbm: 3.3.2.99 and Optuna: 3.0.0 aren't compatible on that end (`cv() got an unexpected keyword argument 'fobj'`). I'll try with Optuna: 3.1.0.dev and Lightgbm: 3.3.2.

**Comment by nzw0301** [comment] 2022-09-07 18:37
I really appreciate your detailed detailed information on your problem!

> I've confirmed that Lightgbm: 3.3.2.99 and Optuna: 3.0.0 aren't compatible on that end (cv() got an unexpected keyword argument 'fobj'). I'll try with Optuna: 3.1.0.dev and Lightgbm: 3.3.2.

https://github.com/optuna/optuna/issues/3646 describes the same error, and it also provides a patch. It might be helpful for your case. 

Since the bug is not reproducible for my environment with the iris dataset and likely comes from lightgbm according to your investigation, I'd like to close this PR. Of course, please feel free to update this PR if you can create a reproducible example or further update!

**Closed by nzw0301** 2022-09-07 18:37 UTC
Labels: bug
