### ISSUE TITLE
Duration of iteration increases as the number of iterations increase, with distributed optimization.

### ISSUE THREAD

**Issue by jt269** [optuna/optuna#5397] opened 2024-04-16 08:59 UTC
### Expected behavior

Expect that runtime of an iteration should not increase so dramatically over time, here is a chart showing the actual increase in iteration duration: 
![image](https://github.com/optuna/optuna/assets/135972473/036a3f27-9b99-4ec4-9592-e5944e3c886f)
The increase in iteration duration decreases the benefits of distributed optimization.

### Environment

- Optuna version: 3.6.1
- Python version: 3.11

### Error messages, stack traces, or logs

```shell
None
```

### Steps to reproduce

1. Create an Optuna study with journal file storage for distributed optimisation.
2. The study is launched by a subprocess loop which calls a separate python file with contains the objective function, this also loads the study and starts the optimisation. This creates multiple workers with the idea to maximise resource usage, in this example 4 workers are created.

```python
# #python code
#parent code

lock_obj = optuna.storages.JournalFileOpenLock(journal_path)
storage = optuna.storages.JournalStorage(
optuna.storages.JournalFileStorage(journal_path, lock_obj=lock_obj),
)

# Create a study
study = optuna.create_study(study_name="multi_cpu", sampler=NSGAIISampler(), direction="maximize", storage=storage, load_if_exists=True)

procs = [subprocess.Popen([sys.executable, script_to_execute, str(i), csv_path]) for i in range(cpu_num)]

for p in procs:
    p.wait()

# Save results
timestamp=datetime.now().strftime("%Y-%m-%d_%H-%M-%S")
f_name=f"{_name}_results_{timestamp}.csv"
df = study.trials_dataframe()
df.to_csv(f_name, index=False)

print(study.best_params)
print(study.best_value)

#worker code
def fun(trial):

    for i in range(num_vars):
        var = trial.suggest_int(f"x{i}", lower_bounds_list[i], upper_bounds_list[i], step=1)

    #send to external program and retrieve result
 
    return objective_value

optuna.logging.set_verbosity(optuna.logging.WARNING)

lock_obj = optuna.storages.JournalFileOpenLock(url)
storage = optuna.storages.JournalStorage(
    optuna.storages.JournalFileStorage(url, lock_obj=lock_obj),
)

study = optuna.load_study(
    study_name="multi_cpu", storage=storage
)

study.optimize(fun,n_trials=max_iter, timeout=max_time)

```

### Additional context (optional)

I have tried various ways to fix this issue and I assume it has to do with the size of the storage as the optimization progresses. Things I have tried:

1. Using RDB storage with postgresql, same result.
2. Trying to delete older trials as they are no longer relevant to the sampler, loaded the journal as a JSON however the format is not easy to edit. The iteration time decreased if I limited the number of stored trials to 1000 however this caused issues with the dashboard and outputting to pandas dataframe. Also requires optimization to be conducted in a loop which is inconvenient.
3. Trying to switch older trials to a FAIL state however this is not possible.

The issue does not appear when using a single worker launched from within the parent code. The increase in iteration duration removes the benefits of distributed optimization.

I have to create workers using subprocess to be able to connect to multiple instances of the external program where the objective function is calculated.

**Comment by jt269** [comment] 2024-04-16 13:59
Thanks for your reply, I am using the NSGAIII sampler which is not shown in that table but I assume it would have the same relationship as NSGAII. NSGAII time per trial should be independent of the number of trials completed.

**Comment by nzw0301** [comment] 2024-04-16 14:09
Thanks. Right, but in `_collect_parent_population` of NSGAIII has for loop over trials, so I'm not sure this sampler is completely independent of the number of finished trials. Sorry I cannot answer clearly because I'm not familiar with this sampler...

**Comment by nzw0301** [comment] 2024-04-16 14:24
Thanks! Could you share the minimal reproducible code with us?

**Comment by jt269** [comment] 2024-04-16 14:48
I have sent an invite to collaborate to you.

**Comment by nzw0301** [comment] 2024-04-16 14:49
Hi thank you for inviting me to your repo, but I believe the core-dev team also needs to access the repo if they investigate the issue. So I would appreciate it if you could create a public repo.

**Comment by jt269** [comment] 2024-04-16 15:00
ok, I have made it public--> https://github.com/jt269/Optuna_share

I am currently testing with a single worker created through a subprocess and that also seems to have the same issue.

**Comment by HideakiImamura** [comment] 2024-04-17 04:52
Thank you for reporting the issue and sharing your code. Given the complexity of the provided code, we are unable to execute it on our end. Could you perhaps provide a minimalistic version of the code that only focuses on and can reproduce this specific issue?

**Comment by jt269** [comment] 2024-04-17 08:38
Hello, I have uploaded a minimalistic version. Thanks.

**Comment by jt269** [comment] 2024-04-19 10:56
Hello, did you manage to reproduce this issue? Thanks

**Comment by not522** [comment] 2024-05-14 07:29
Sorry for my late response and thank you for sharing the minimum reproducible code.
I tried running your code, but unfortunately I couldn't reproduce the slowdown in my environment.
Could you share your results for the minimum reproducible code?

**Comment by jt269** [comment] 2024-05-14 11:40
Thanks for your reply. I found out what the issue was, If you load a study using "optuna.study.load_study" the settings for the study are not loaded and they revert to default. Which in this case meant the sampler was changing from NSGAIII to the BaseSampler which then has increasing suggestion time dependant on the number of previous samples. To get around this "optuna.study.create_study" with" load_if_exists = True" or "optuna.study.load_study" can be used however all study settings must be replicated.

**Comment by not522** [comment] 2024-05-15 05:38
Thank you for sharing. To restore the Study state with `load_study`, you need to specify `NSGAIIISampler` in the sampler argument.

If the problem is resolved, I would like to close the issue, what do you think?

**Closed** 2024-05-15 09:35 UTC
Labels: bug

**Comment by johnasiano** [comment] 2025-01-09 13:33
> Thanks for your reply. I found out what the issue was, If you load a study using "optuna.study.load_study" the settings for the study are not loaded and they revert to default. Which in this case meant the sampler was changing from NSGAIII to the BaseSampler which then has increasing suggestion time dependant on the number of previous samples. To get around this "optuna.study.create_study" with" load_if_exists = True" or "optuna.study.load_study" can be used however all study settings must be replicated.

What part of the code base does this 'revert to [BaseSampler]' occur? Is it here: https://github.com/optuna/optuna/blob/755195c3bfc25d181e3f9d248974f3bf2eac5efc/optuna/study/study.py#L1295, on line 1299?
