### ISSUE TITLE
lightgbm tuner can't handle 'ndcg' metric

### ISSUE THREAD

**Issue by kondo-kk** [optuna/optuna#909] opened 2020-02-10 05:42 UTC
When I set 'ndcg' as metric, ligbtgbm_tuner raise key error at `booster.best_score[valid_name][metric]`

## Expected behavior

 Probably, 'metric' variable at the tuner is 'ndcg' but `booster.best_score` dictionary at the booster class stores 'ndcg@20'. So the  KeyError has raised.

## Environment

- Optuna version: 1.1.0
- Python version: 3.5.3
- OS: Debian GNU/Linux 9
- (Optional) Other libraries and their versions:

## Error messages, stack traces, or logs

```
File "<ipython-input-8-44094cd56040>", line 32, in train_lgbm_ranking
    early_stopping_rounds=early_stopping_rounds, callbacks=None, best_params=best_params, tuning_history=tuning_history)
  File "/home/user/.local/lib/python3.5/site-packages/optuna/integration/lightgbm_tuner/__init__.py", line 23, in train
    booster = auto_booster.run()
  File "/home/user/.local/lib/python3.5/site-packages/optuna/integration/lightgbm_tuner/optimize.py", line 379, in run
    self.tune_feature_fraction()
  File "/home/user/.local/lib/python3.5/site-packages/optuna/integration/lightgbm_tuner/optimize.py", line 425, in tune_feature_fraction
    self.tune_params([param_name], len(param_values), sampler)
  File "/home/user/.local/lib/python3.5/site-packages/optuna/integration/lightgbm_tuner/optimize.py", line 487, in tune_params
    study.optimize(objective, n_trials=n_trials, catch=())
  File "/home/user/.local/lib/python3.5/site-packages/optuna/study.py", line 302, in optimize
    gc_after_trial, None)
  File "/home/user/.local/lib/python3.5/site-packages/optuna/study.py", line 538, in _optimize_sequential
    self._run_trial_and_callbacks(func, catch, callbacks, gc_after_trial)
  File "/home/user/.local/lib/python3.5/site-packages/optuna/study.py", line 550, in _run_trial_and_callbacks
    trial = self._run_trial(func, catch, gc_after_trial)
  File "/home/user/.local/lib/python3.5/site-packages/optuna/study.py", line 569, in _run_trial
    result = func(trial)
  File "/home/user/.local/lib/python3.5/site-packages/optuna/integration/lightgbm_tuner/optimize.py", line 240, in __call__
    val_score = self._get_booster_best_score(booster)
  File "/home/user/.local/lib/python3.5/site-packages/optuna/integration/lightgbm_tuner/optimize.py", line 142, in _get_booster_best_score
    val_score = booster.best_score[valid_name][metric]
KeyError: 'ndcg'
```

## Steps to reproduce

1. set "ndcg" as metric, "lambdarank" as objective.
2. set 20 as "ndcg_eval_at" 
3. train start

**Comment by toshihikoyanase** [comment] 2020-02-10 11:05
Hi @kondo-kk,
Thank you for reporting the issue.
I think I can reproduce the error in [this notebook](https://colab.research.google.com/drive/1NH3CtNuo7hsZWi4u7E1YOPHKWyP-7x0o). It probably has some problems because I'm not familiar with learning-to-rank using LightGBM.
If you have any comments or questions, please let me know. Or, it would be a great help of us if you share your working examples.

**Comment by toshihikoyanase** [comment] 2020-02-26 04:39
Hi @kondo-kk ,

https://github.com/optuna/optuna/pull/912 was merged into the master branch today. I think you can use `ndcg` metrics with LightGBM Tuner now if you install the development version of Optuna (see https://optuna.readthedocs.io/en/latest/installation.html).

Please let me know if you have further problems.

**Comment by kondo-kk** [comment] 2020-02-26 08:45
@toshihikoyanase 
Thank you for your quick response and letting me know.

**Comment by toshihikoyanase** [comment] 2020-02-27 03:00
@kondo-kk 
Although @smly reported that https://github.com/optuna/optuna/pull/912 needed a follow-up (https://github.com/optuna/optuna/issues/960), I think that this issue has been resolved. So, let me close it.
Please feel free to re-open it or create new issues.

**Closed by toshihikoyanase** 2020-02-27 03:00 UTC
Labels: bug
