### ISSUE TITLE
Crash when metric is NaN

### ISSUE THREAD

**Issue by bosmart** [optuna/optuna#2809] opened 2021-07-15 09:15 UTC
Using the FastaiV2 callback, when the metric becomes NaN, the error is: 

`sqlalchemy.exc.IntegrityError: (sqlite3.IntegrityError) NOT NULL constraint failed: trial_intermediate_values.intermediate_value
[SQL: INSERT INTO trial_intermediate_values (trial_id, step, intermediate_value) VALUES (?, ?, ?)]
[parameters: (52, 20, nan)]`

My workaround is (inside FastAIV2PruningCallback):

```   
    def after_epoch(self) -> None:
        super().after_epoch()
        # self.idx is set by TrackTrackerCallback

        out = self.recorder.final_record[self.idx]
        if np.isnan(out):
            out = np.inf if self.trial.study.direction == optuna.study.StudyDirection.MINIMIZE else -np.inf
        self.trial.report(out, step=self.epoch)

        if self.trial.should_prune():
            raise CancelFitException()
```

**Comment by jkterry1** [comment] 2021-08-09 12:26
The referenced issue I created explains why this would happen in practice including a link to an upstream issue. Also note that this impacts both NaN and inf.

**Comment by lsc64** [comment] 2021-08-16 13:27
Duplicate of https://github.com/optuna/optuna/issues/2169

**Comment by nzw0301** [comment] 2021-08-16 13:51
@lsc64 thank you for letting us know about it! Indeed, this issue is already known. Let me close this issue.

**Closed by nzw0301** 2021-08-16 13:51 UTC
