### ISSUE TITLE
Easy parallelization mysql password

### ISSUE THREAD

**Issue by gkourogiorgas** [optuna/optuna#2677] opened 2021-05-14 10:28 UTC
I am trying to run the tutorial on easy parallelization:
https://optuna.readthedocs.io/en/stable/tutorial/10_key_features/004_distributed.html
Mysql is installed via brew on my mac.
To create the "example" database I run the command with `-p` parameter:
`mysql -u root -e "CREATE DATABASE IF NOT EXISTS example" -p`
And then when I run:
`optuna create-study --study-name "distributed-example" --storage "mysql://root@localhost/example"`
I get:
`(MySQLdb._exceptions.OperationalError) (1045, "Access denied for user 'root'@'localhost' (using password: NO)")
(Background on this error at: http://sqlalche.me/e/14/e3q8)`

Any idea how to overcome this with optuna CLI?

**Comment by toshihikoyanase** [comment] 2021-05-14 10:48
Hi @gkourogiorgas 
I guess the DB URL requires the password. You can place password between username and hostname as follows:
`mysql://root:<password>@localhost/example`
Fore more details, please refer to the following document:
https://docs.sqlalchemy.org/en/14/core/engines.html#database-urls

**Comment by gkourogiorgas** [comment] 2021-05-14 11:07
Thanks. It is not about optuna, but do you know how I can remove the need for a password for mysql in Mac.
I have googled it and strangely all i see is posts on how to reset the password.
Just asking

**Comment by toshihikoyanase** [comment] 2021-05-14 13:15
> do you know how I can remove the need for a password for mysql in Mac.

I don't have macOS machines right now, so I checked it using docker containers.
I hesitated to remove the root password, so I created a new user without password. Then, I could use MySQL from optuna.

1. I created the `optuna` user and the `optuna` database for the optuna experiment. Then, I granted all privileges to the `optuna` user. 
```sql
CREATE USER optuna@"%";
CREATE DATABASE optuna;
GRANT ALL ON optuna.* TO optuna@"%";
```

2. I ran the optimization with the `optuna` database.
```python
>>> import optuna
>>> study = optuna.create_study(storage="mysql+pymysql://optuna@localhost/optuna")
[I 2021-05-14 13:05:25,834] A new study created in RDB with name: no-name-702d0758-84e4-4d46-bb90-421cacbf40b5
>>> study.optimize(lambda t: t.suggest_float("x", -10, 10) ** 2, n_trials=20)
[I 2021-05-14 13:05:58,695] Trial 0 finished with value: 47.761654566567415 and parameters: {'x': -6.9109807239325605}. Best is trial 0 with value: 47.7617.
[I 2021-05-14 13:05:58,740] Trial 1 finished with value: 77.58651166678466 and parameters: {'x': 8.808320592870395}. Best is trial 0 with value: 47.7617.
```

3. I confirmed that the optimization result was preserved in MySQL database using Optuna CLI.
```bash
$ docker exec -it mysql bash
root@9c54c52bfc0c:/# optuna studies --storage mysql+pymysql://optuna@localhost/optuna
+----------------------------------------------+---------------+----------+---------------------+
| NAME                                         | DIRECTION     | N_TRIALS | DATETIME_START      |
+----------------------------------------------+---------------+----------+---------------------+
| no-name-702d0758-84e4-4d46-bb90-421cacbf40b5 | ('MINIMIZE',) |       20 | 2021-05-14 13:05:59 |
+----------------------------------------------+---------------+----------+---------------------+
```

**Comment by gkourogiorgas** [comment] 2021-05-14 14:21
Thanks a lot for the help

**Comment by nzw0301** [comment] 2021-05-22 07:32
let me close this issue since the original question is supposed to be answered. Please feel free to reopen this issue if you have a still problem.

**Closed by nzw0301** 2021-05-22 07:32 UTC
Labels: question
