### ISSUE TITLE
2 tests fail

### ISSUE THREAD

**Issue by yurivict** [optuna/optuna#5658] opened 2024-09-03 08:12 UTC
### Expected behavior

n/a

### Environment

- Optuna version: 4.0.0
- Python version: 3.11
- OS: FreeBSD 14.1
- (Optional) Other libraries and their versions:

### Error messages, stack traces, or logs

```shell
========================================================================================= FAILURES ==========================================================================================
_____________________________________________________________________________ test_deprecation_class_decorator ______________________________________________________________________________

    def test_deprecation_class_decorator() -> None:
        deprecated_version = "1.1.0"
        removed_version = "3.0.0"
        decorator_deprecation = _deprecated.deprecated_class(deprecated_version, removed_version)
        assert callable(decorator_deprecation)
    
        decorated_class = decorator_deprecation(_Sample)
        assert decorated_class.__name__ == "_Sample"
        assert decorated_class.__init__.__name__ == "__init__"
>       assert decorated_class.__doc__ == _deprecated._DEPRECATION_NOTE_TEMPLATE.format(
            d_ver=deprecated_version, r_ver=removed_version
        )
E       AssertionError: assert '.. warning::...tag/v1.1.0.\n' == '\n\n.. warni...tag/v1.1.0.\n'
E         
E         - 
E         + .. warning::
E         +     Deprecated in v1.1.0. This feature will be removed in the future. The removal of this
E         +     feature is currently scheduled for v3.0.0, but this schedule is subject to change.
E         +     See https://github.com/optuna/optuna/releases/tag/v1.1.0.
E           ...
E         
E         ...Full output truncated (4 lines hidden), use '-vv' to show

tests/test_deprecated.py:87: AssertionError
_____________________________________________________________________________ test_experimental_class_decorator _____________________________________________________________________________

    def test_experimental_class_decorator() -> None:
        version = "1.1.0"
        decorator_experimental = _experimental.experimental_class(version)
        assert callable(decorator_experimental)
    
        decorated_class = decorator_experimental(_Sample)
        assert decorated_class.__name__ == "_Sample"
        assert decorated_class.__init__.__name__ == "__init__"
>       assert decorated_class.__doc__ == _experimental._EXPERIMENTAL_NOTE_TEMPLATE.format(ver=version)
E       AssertionError: assert '.. note::\n ...tag/v1.1.0.\n' == '\n\n.. note:...tag/v1.1.0.\n'
E         
E         - 
E         + .. note::
E         +     Added in v1.1.0 as an experimental feature. The interface may change in newer versions
E         +     without prior notice. See https://github.com/optuna/optuna/releases/tag/v1.1.0.
E           
E           .. note::
E               Added in v1.1.0 as an experimental feature. The interface may change in newer versions
E               without prior notice. See https://github.com/optuna/optuna/releases/tag/v1.1.0.

tests/test_experimental.py:79: AssertionError
========================================================================= 2 failed, 370 passed in 301.25s (0:05:01) =========================================================================
*** Error code 1
```

### Steps to reproduce

pytest

**Comment by nzw0301** [comment] 2024-09-03 08:51
Hmm, I could not reproduce the error with the latest stable Optuna (4.0.0) and the latest comment: https://github.com/optuna/optuna/commit/d00b9509b461c24dd0b2dbb2ad8561973d4ad929. Could you elaborate on what you want to do with pytest? To send a pull request, you can ignore the error on your local machine since they are tests if the introduced changes are not related to this test file.

**Comment by nzw0301** [comment] 2024-09-07 03:42
Since this is not reproducible and no additional update so far, let me close this issue.

**Closed by nzw0301** 2024-09-07 03:42 UTC
Labels: bug
