### ISSUE TITLE
trial.suggest_int uses RandomSampler instead of CmaEsSampler

### ISSUE THREAD

**Issue by koh-joshua** [optuna/optuna#1569] opened 2020-07-29 11:17 UTC
All my parameters are using trial.suggest_int.
Tried optuna.samplers.CmaEsSampler but performance really bad. Many parameters used RandomSampler and objective score, R2 was very low and seemed static, R2 = 0.30
Tried optuna.integration.CmaEsSampler and performance was slightly better, R2 = 0.58 - 0.60 but also many parameters was sampled using RandomSampler.
The same study using TPESampler gives R2 = 0.749, no problems.

Some representative codes:

def objective (trial):
    params_list =[]
    n_params = trial.suggest_int('n_params', 3, 5)
    param1 = trial.suggest_int('param1', 0, 1200)
    param2 = trial.suggest_int('param2', 0, 1199)
    params_list.append(param1)
    params_list.append(param2) 
    if n_params >=3: 
            param3 = trial.suggest_int('param3', 0, 1198)
            params_list.append(param3)
    if n_params >=4:
            param4 = trial.suggest_int('param4', 0, 1197)
            params_list.append(param4)
   if n_params >=5:
          param5 = trial.suggest_int('param5', 0, 1196)
          params_list.append(param5)
    model = model(params_list)
    score = model.evaluate(x_test, y_test)   # R2 score
    return score
 
study = optuna.create_study(direction='maximize', sampler=optuna.samplers.CmaEsSampler)
study.optimize(objective, n_trials=10000, n_jobs=-1)

I have noticed that **RandomSampler is always used on params 3, 4, 5 i.e. those that were in the conditional if statements.** 

I expect performance to be comparable to TPESampler and sampling is done using the CmaEsSampler.

## Environment

- Optuna version: 2.0
- Python version: 3.7
- OS: win10 64-bit
- (Optional) Other libraries and their versions: 

## Error messages, stack traces, or logs

```
# error messages, stack traces, or logs
Example error messages:
[W 2020-07-29 20:58:44,714] The parameter 'param3' in trial#9993 is sampled independently by using `RandomSampler` instead of `CmaEsSampler` (optimization performance may be degraded). You can suppress this warning by setting `warn_independent_sampling` to `False` in the constructor of `CmaEsSampler`, if this independent sampling is intended behavior.
[W 2020-07-29 20:58:44,714] The parameter 'param4' in trial#9994 is sampled independently by using `RandomSampler` instead of `CmaEsSampler` (optimization performance may be degraded). You can suppress this warning by setting `warn_independent_sampling` to `False` in the constructor of `CmaEsSampler`, if this independent sampling is intended behavior.
[W 2020-07-29 20:58:44,714] The parameter 'param5' in trial#9996 is sampled independently by using `RandomSampler` instead of `CmaEsSampler` (optimization performance may be degraded). You can suppress this warning by setting `warn_independent_sampling` to `False` in the constructor of `CmaEsSampler`, if this independent sampling is intended behavior.

**Comment by c-bata** [comment] 2020-07-29 11:34
Thank you for reporting the problem.
I guess the problem is related to #1557 and fixed at #1558. Could you try to use the master branch of Optuna?

```
$ pip install -U git+https://github.com/optuna/optuna.git
```

I'm not sure but the performance issue may be also resolved.

**Comment by c-bata** [comment] 2020-07-29 13:47
Ah, sorry. This problem is not related to #1558 and this is not a bug.

CmaEsSampler is based on relative sampling which is only available if all trials sample the same parameters (See [here](https://optuna.readthedocs.io/en/stable/reference/generated/optuna.samplers.BaseSampler.html#optuna.samplers.BaseSampler) for details about relative sampling). Your objective function switch the search space at each trials ( `params4` and `params5` are not sampled if `n_params` returns `3`). As a result, all parameters are sampled by RandomSampler.

**Comment by koh-joshua** [comment] 2020-07-30 04:24
Thank you for your super quick response and explanation. You guys are totally amazing! Perhaps I can shout the Optuna team some beer and sake in the future when I drop by Tokyo. Thank!

**Comment by koh-joshua** [comment] 2020-08-01 12:37
Hi c-bata, I have run a few studies using CmaEsSampler but the performance is very poor compared to TPESampler. When I export the study results into a dataframe, I noticed the column 'system_attrs_cma: generation' has 'nan' values in them. Is this a concern?

**Comment by c-bata** [comment] 2020-08-01 12:49
Could you check your search space? As I commented above, `CmaEsSampler` does not support dynamic search space. So I guess it is fallen back to RandomSampler.

**Comment by koh-joshua** [comment] 2020-08-01 13:47
I have change my codes to this:

def objective (trial):
param1 = trial.suggest_int('param1', 0, 1200)
param2 = trial.suggest_int('param2', 0, 1199)
param3 = trial.suggest_int('param3', 0, 1198)
param4 = trial.suggest_int('param4', 0, 1197)
param5 = trial.suggest_int('param5', 0, 1196)
param_list = [param1, param2, param3, param4, param5]
model = model(params_list)
score = model.evaluate(x_test, y_test) # R2 score
return score

sampler = optuna.samplers.CmaEsSampler(warn_independent_sampling=True)
study = optuna.create_study(direction='maximize', sampler=sampler)
study.optimize(objective, n_trials=10000, n_jobs=-1)

I don't think it is using RandomSampler as normally I would see warning message 'RandomSampler used instead of CmaEsSampler'?

**Comment by c-bata** [comment] 2020-08-01 14:02
Hmm...

> I don't think it is using RandomSampler as normally I would see warning message 'RandomSampler used instead of CmaEsSampler'?

Yes. Your search space is not dynamic and seems not to fall back to RandomSampler.
I will benchmark CMA-ES on integer search space (I've ever benchmarked CMA-ES with float search spaces).

Thank you for reporting!

**Comment by koh-joshua** [comment] 2020-08-01 14:06
Can't wait for your miracle fix. I want to compare TPE vs CMA-ES. Any plans for other optimization algorithms like particle swarm optimization (PSO) or genetic algorithm (GA)?

**Comment by c-bata** [comment] 2020-08-01 14:12
Sorry, I'm not planning to add those algorithms.
It may be useful to check following samplers.

* [SkoptSampler](https://optuna.readthedocs.io/en/stable/reference/generated/optuna.integration.SkoptSampler.html#optuna.integration.SkoptSampler): Sampler which uses scikit-optimize for Gaussian process based bayesian optimization.
* [PyCmaSampler](https://optuna.readthedocs.io/en/stable/reference/generated/optuna.integration.PyCmaSampler.html#optuna.integration.PyCmaSampler): Another CMA-ES sampler which uses pycma.

**Comment by koh-joshua** [comment] 2020-08-01 14:23
Thank you. I am trying PyCmaSampler...it is slow....
I wanted to compare a Bayesian based sampler (TPE) to evolution based sampler (CMA-ES, PSO or GA). I think your cma-es implementation is the best, because it is fast. Fingers crossed the bug will be flushed out. Thanks!

**Comment by c-bata** [comment] 2020-08-01 14:46
Thank you!
If it is improved by PyCmaSampler, we can conclude that CmaEsSampler has something problem.
I'm waiting for your updates.

**Comment by koh-joshua** [comment] 2020-08-03 01:57
PyCmaSampler performance is similar to RandomSearch, both giving R2 = 0.65 - 0.69, TPE giving R2 = 0.70 - 0.75. 
So, I am not sure if PyCmaSampler is really working or it's a situation where CMA-ES is not suitable? I think there's mention that if variance for objective function is large, CMA-ES is not suitable? I am not sure whether this is the case.

**Comment by c-bata** [comment] 2020-08-04 18:15
Thank you for reporting! You mean CmaEsSampler performs lower than PyCmaSamlper right?

> PyCmaSampler took over 2 days to complete 20,000 trials (on a Threadripper 3790X 32-cores!!!). I am not sure if this is normal?

Yes, PyCmaSampler is slow.

**Comment by koh-joshua** [comment] 2020-08-06 04:47
Yes, CmaEsSampler performs lower than PyCmaSampler. 

Also, a general question for the Optuna team. I noticed significant speed degradation as a study progresses (using TPESampler), noticeably beyond 10,000 trials, it gets slower and slower. Once it reaches 100,000 trials, it is like snail's pace. I am using n_jobs=-1 for my study. Also, switching over to distributed parallel processing using postgresql also shows same performance behaviour - speed degrades as study progresses.

**Comment by c-bata** [comment] 2020-08-06 13:04
> Yes, CmaEsSampler performs lower than PyCmaSampler.

I see. Thank you for your information!

> Also, a general question for the Optuna team. I noticed significant speed degradation as a study progresses (using TPESampler), noticeably beyond 10,000 trials, it gets slower and slower. Once it reaches 100,000 trials, it is like snail's pace. I am using n_jobs=-1 for my study. Also, switching over to distributed parallel processing using postgresql also shows same performance behaviour - speed degrades as study progresses.

As you noticed, it's difficult to evaluate 10,000+ trials on Optuna. It is due to the design of storage classes (Please check https://github.com/optuna/optuna/issues/1170 for more details).

**Comment by c-bata** [comment] 2020-09-16 13:15
Hi @koh-joshua. I found the bug on my CMAES library and fixed it at v0.6.1. So your problem might be resolved after upgrade cmaes library.
https://github.com/CyberAgent/cmaes/releases/tag/v0.6.1

**Comment by c-bata** [comment] 2020-09-16 13:21
By the way, can I close this issue?

If your problem will not be resolved, please post the entire code to reproduce the problem. I understand that this may not be possible, but it is hard to fix the performance issue without reproducing.

**Comment by c-bata** [comment] 2020-09-18 10:56
Hi! CmaEsSampler is completely broken if study_direction is maximize like your script (See #1848). I'm sorry.
I guess this problem will be resolved after merging #1849.

**Comment by koh-joshua** [comment] 2020-09-20 22:30
Does that mean if I apply negative R2 as the objective function score (i.e. direction=minimize), it may actually work?

**Comment by c-bata** [comment] 2020-09-21 03:00
Yes, I guess.

**Comment by koh-joshua** [comment] 2020-09-22 02:20
I have another separate question. I have noticed CPU usage under multicore parallel processing (joblib) for optune 2.1.0 is very low and much slower compared to ver 2.0.0. Has any significant changes been made to the way multiple studies are handled? I noticed separate studies being created in memory - is this something new?

**Comment by c-bata** [comment] 2020-09-22 03:25
I have no idea. Could you open a new issue?

**Comment by c-bata** [comment] 2020-10-01 05:15
Let me close this issue because #1849 is merged. If you still bump the same issue, please feel free to reopen.

**Closed by c-bata** 2020-10-01 05:15 UTC
Labels: bug
