### ISSUE TITLE
Why does optuna doesn's show the parameters it used during the optimization?

### ISSUE THREAD

**Issue by ZumbiAzul** [optuna/optuna#2521] opened 2021-03-25 11:18 UTC
While in optimization mode, optuna should tell which trial was the best listing the cost and hyperparameters.
Here is what I get:
```
[I 2021-03-25 11:48:50,253] Trial 55 finished with value: 4.0283379554748535 and parameters: {}. Best is trial 29 with value: 3.9094388484954834.
```
As you see parameters are given as just empty curly brackets.

The command `print(study.best_trial)` gives:
```
FrozenTrial(number=29, value=3.9094388484954834, datetime_start=datetime.datetime(2021, 3, 25, 3, 20, 52, 275373), datetime_complete=datetime.datetime(2021, 3, 25, 3, 39, 39, 340580), params={}, distributions={}, user_attrs={}, system_attrs={}, intermediate_values={}, trial_id=30, state=TrialState.COMPLETE)
```
The command `print("  Value: ", trial.value)` gives:
```
  Value:  3.9094388484954834
```
Then I try these commands:
```
print("  Params: ")
for key, value in trial.params.items():
    print("    {}: {}".format(key, value))
```
and they result in emptiness:
```
  Params: 
```

Although it seems that optuna indeed suggests parameters, but why are they somehow not recorded within the framework?

**Comment by nzw0301** [comment] 2021-03-25 11:37
Could you share your reproducible code for your question? Otherwise, we might not investigate your question because it is hard to do so...

**Comment by ZumbiAzul** [comment] 2021-03-25 12:55
> Could you share your reproducible code for your question? Otherwise, we might not investigate your question because it is hard to do so...

I am not sure if it is possible to post a reproducible code here. I guess, your reply tells that it is not common and has not happened previously very often.

What I noticed that after the first trial the best parameters are reported by optuna:
```
[I 2021-03-25 13:46:11,920] Trial 0 finished with value: 3.228217124938965 and parameters: {"network_hyperparams['batch_size'][0]": 259, "network_hyperparams['learning_rate'][0]": 0.004377455885218632, 'lrd': 2, "network_hyperparams['number_of_epochs'][0]": 3}. Best is trial 0 with value: 3.228217124938965.
```
But after the next trial I start getting:
```
[I 2021-03-25 13:48:11,817] Trial 1 finished with value: 3.2964870929718018 and parameters: {}. Best is trial 0 with value: 3.228217124938965.
```

**Comment by nzw0301** [comment] 2021-03-25 14:02
Okay... fair enough. How about only the objective function?

**Comment by nzw0301** [comment] 2021-03-25 14:50
I do not fully understand the logic, but it sounds sampling part for `network_hyperparams`  is not performed.

**Comment by ZumbiAzul** [comment] 2021-03-25 15:08
> I do not fully understand the logic, but it sounds sampling part for `network_hyperparams` is not performed.

Could you please expand?

**Comment by nzw0301** [comment] 2021-03-25 15:13
If `network_hyperparams` is not in reported `params`, I think they were not sampled in the objective. Could you check the hyper-parameters are actually sampled in each trial?

**Comment by nzw0301** [comment] 2021-03-25 15:21
Again, I'm afraid that I cannot understand what is a bug in this issue. I would like to kindly ask you to follow the issue template for the bug report. Otherwise, this issue won't be checked because it will take too much time to understand it.

I suppose that using markdown, providing reproducible code example, and clarifying dependencies are really helpful to understand the issue.

Best regards,

**Comment by ZumbiAzul** [comment] 2021-03-25 17:01
I found a solution.
It seems that this bug arises when I try to suggest a `variable`, which was already created/reassigned before.
When I initialize the `variable` as an empty list, then optuna behaves normally.

**Comment by nzw0301** [comment] 2021-03-25 17:14
Awesome! Could you close this issue? I suppose the issue was resolved by yourself.

**Closed** 2021-03-25 17:36 UTC
Labels: question
