### ISSUE TITLE
Can't retrieve lightgbm model's best_iteration after Optuna optimization

### ISSUE THREAD

**Issue by YingJie-Zhao** [optuna/optuna#5363] opened 2024-03-27 06:07 UTC
### Expected behavior

I was using Optuna to optimize my LightGBM model. At the same time I was using LightGBM callbacks ```early_stopping(50)``` to early stop the iterations. 
```python
def objective(trial): 
    model = lgb.train(params, callbacks=[early_stopping(50)])
    trial.set_user_attr(key='best_booster', value=model)
```
I have saved the best model in loops of optimization, and retrieved the best model(best booster) from the ```user_attr```. 
```python
def save_best_booster(study, trial):
    if study.best_trial.number == trial.number:
        study.set_user_attr(key='best_booster', value=trial.user_attrs['best_booster'])

study.optimize(
    func, 
    n_trials=30,
    show_progress_bar=True,
    callbacks=[save_best_booster]
)

trial = study.best_trial
best_model=study.user_attrs['best_booster']
```
Since the early_stopping callbacks was set, the training output logs showed some content like this below:
```python
Early stopping, best iteration is:
[30]	train_set's auc: 0.982083	valid_set's auc: 0.874471
Training until validation scores don't improve for 100 rounds
```
Assuming that the auc value above ```valid_set's auc: 0.874471```was indeed the best value from all iterations, the best_iteration should be ```[30]``` as showed above.

However, I got -1 from invoking ```best_model.best_iteration``` like this below:
```
In: print(best_model.best_iteration)
Out: -1
```
My question is: How can I get the correct ```best_iteration``` value from the best model retrieved from ```study``` object? Looks like the model returned from ```train``` API was unexpectedly modified by ```study``` object.

Thanks to whom may solving my problem!
Looking forward to your reply :)

### Environment

- Optuna version: 3.6.0
- Python version: 3.9
- OS: linux x86
- (Optional) Other libraries and their versions:
Optuna_Integration: 3.6.0

### Error messages, stack traces, or logs

```
In: print(best_model.best_iteration)
Out: -1
```

### Reproducible example

```python
from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import train_test_split
from sklearn.metrics import roc_auc_score
import lightgbm as lgb
import optuna
from lightgbm import early_stopping

dataset = load_breast_cancer()
x_train, x_test, y_train, y_test = train_test_split(dataset.data, dataset.target, test_size=0.2)

def objective(trial, train_set, valid_set, num_iterations): 
    params = {
        'objective':'binary', 
        'metric': ['auc'],
        'verbosity':-1, 
        'learning_rate': trial.suggest_float('learning_rate', 0.01, 0.5)
    }

    pruning_callback = optuna.integration.LightGBMPruningCallback(trial, 'auc', valid_name='valid_set')
    
    model = lgb.train(
        params,
        num_boost_round=num_iterations,
        train_set=train_set, 
        valid_sets=[train_set, valid_set], 
        valid_names=['train_set', 'valid_set'],
        callbacks=[pruning_callback, early_stopping(50)]
    )
    
    trial.set_user_attr(key='best_booster', value=model)

    prob_pred = model.predict(x_test, num_iteration=model.best_iteration)
    return roc_auc_score(y_test, prob_pred, labels=[0,1])

train_set = lgb.Dataset(x_train, label=y_train)
valid_set = lgb.Dataset(x_test, label=y_test)
func = lambda trial: objective(trial=trial, train_set=train_set, valid_set=valid_set, num_iterations=num_iterations)

num_iterations = 100
study = optuna.create_study(
    pruner=optuna.pruners.HyperbandPruner(), 
    direction='maximize'
)

def save_best_booster(study, trial):
    if study.best_trial.number == trial.number:
        study.set_user_attr(key='best_booster', value=trial.user_attrs['best_booster'])

study.optimize(
    func, 
    n_trials=30,
    show_progress_bar=True,
    callbacks=[save_best_booster]
)

trial = study.best_trial
best_model=study.user_attrs['best_booster']

print(best_model.best_iteration)
```

**Comment by YingJie-Zhao** [comment] 2024-03-27 08:04
BTW，this problem has been issued at https://github.com/microsoft/LightGBM/issues/6384#issue-2207690576 and currently didn't found any code related to lightgbm could cause this situation. So I think may be turning into Optuna developer's help could be better.

**Comment by HideakiImamura** [comment] 2024-03-27 08:36
Perhaps this is due to the migration of the integration module to the optuna_integration package. We have supported backward compatibility to function without re-writing the code, but you will need to install the optuna_integration package. Could you please run `pip install optuna_integration`?

**Comment by YingJie-Zhao** [comment] 2024-03-27 09:25
The reproducible example above was tested with both ```optuna 3.6.0``` and ```optuna_integration 3.6.0```  installed. So I think may be this was not about the version.

**Comment by nzw0301** [comment] 2024-03-27 13:28
I suspect that this is lightgbm issue; when I copy `model` with `copy.copy` or `copy.deepcopy`, both copy models have `best_iteration=-1`.

**Comment by YingJie-Zhao** [comment] 2024-03-27 13:34
Thanks to your reply.

I tried printing ```best_iteration``` both inside and outside the ```objective``` function, seems like the inner ```print``` works well but the outer ```print``` returns ```-1```. See https://github.com/microsoft/LightGBM/issues/6384#issuecomment-2020748989

**Comment by nzw0301** [comment] 2024-03-27 13:47
Thank you for sharing it. I've left the comment on this as https://github.com/microsoft/LightGBM/issues/6384#issuecomment-2022812532.

**Comment by nzw0301** [comment] 2024-03-27 14:43
I think we can close this issue because the workaround is discussed on the lightgbm issue helpfully. Alternatively we might save the best mode as a file and update the best model's file name similarly to the shared script.  


Personally I appreciate you for your minimal reproducible code and investigating the copy logics in lightgbm repo!

**Closed by nzw0301** 2024-03-27 14:43 UTC
Labels: bug
