### ISSUE TITLE
Suggesting same parameters in several trials with discrete parameter grid

### ISSUE THREAD

**Issue by oasidorshin** [optuna/optuna#5440] opened 2024-05-11 06:14 UTC
### Expected behavior

I encountered following issue:
If parameter grid is discrete in nature (i.e. made of suggest_categorical only), optuna suggests same parameters in several trials (in my case in 3 out of 20), wasting computing time. Keep in mind that the number of possible parameter permutations in my case is higher than 20.

I think that it is needed to hash-check the suggested combination of parameters for a duplicate.

### Environment

- Optuna version: 3.6.1
- Python version: 3.7.12
- OS: Linux

### Error messages, stack traces, or logs

```shell
None
```

### Steps to reproduce

Was described in the beginning, but willing to provide additional code if necessary.

**Comment by nzw0301** [comment] 2024-05-11 08:52
Optuna cares about stochastic objective function too, so this is not a bug and this seems duplicated with https://github.com/optuna/optuna/issues/2021. Let me close this issue.

**Closed by nzw0301** 2024-05-11 08:52 UTC
Labels: feature
