### ISSUE TITLE
suggest_*** returns numpy.float64 instead of float when optuna.samplers.TPESampler(multivariate=True) is used

### ISSUE THREAD

**Issue by hal-314** [optuna/optuna#1952] opened 2020-10-22 17:05 UTC
suggest_*** functions that should return float returns numpy.float64 under multivariate=True in Optuna 2.2
I tested `trial.suggest_uniform` and `trial.suggest_float`

## Reproducible examples (optional)

```python
import optuna
def objective(trial):
    x = trial.suggest_uniform('x', -10, 10)
    #x = trial.suggest_float('x', -10, 10)
    print(type(x))
    return (x - 2) ** 2

print("Univariate:")
study = optuna.create_study(sampler=optuna.samplers.TPESampler(multivariate=False))
study.optimize(objective, n_trials=15)
print('Multivariate:')
study = optuna.create_study(sampler=optuna.samplers.TPESampler(multivariate=True))
study.optimize(objective, n_trials=15)
```
It prints:
```
Univariate:
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
Multivariate:
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'numpy.float64'>
<class 'numpy.float64'>
<class 'numpy.float64'>
<class 'numpy.float64'>
<class 'numpy.float64'>
```

**Comment by toshihikoyanase** [comment] 2020-10-23 06:59
Thank you for your report. I reproduced the issue in this [notebook](https://colab.research.google.com/drive/15GVHYzUCwU_lrPHDHPMDZSKtfophun04?usp=sharing).

I think this is due to the lack of type casting in `TPESampler._compare_multivariate`. Its return values should be `Dict[str, Union[float, int]]`, but it seems to return `Dict[str, Union[np.float, np.int]]`.

https://github.com/optuna/optuna/blob/92b8842c42c1d028ce4a15f50e4dfe45e900bd81/optuna/samplers/_tpe/sampler.py#L657-L680

If so, we can fix it with the following change:

```diff
-            return {k: v[best] for k, v in multivariate_samples.items()}
+            return {k: v[best].item() for k, v in multivariate_samples.items()}
```

I think this issue can be `contribution-welcome`, so let me add the label.

**Comment by toshihikoyanase** [comment] 2020-10-26 00:48
@hal-314 
#1955 resolved this issue, so let me close it. Please feel free to re-open it or create a new one if you have further comments.

**Closed by toshihikoyanase** 2020-10-26 00:48 UTC
Labels: Hacktoberfest, bug, contribution-welcome, optuna.samplers
