### ISSUE TITLE
Using the MLFlow Callback error 'Connection' object has no attribute 'connect' in Google Colab

### ISSUE THREAD

**Issue by FranLucchini** [optuna/optuna#4391] opened 2023-02-03 15:01 UTC
### Expected behavior

I expected the `optuna.integration.MLflowCallback` example shown in the docs to work correctly and not trigger an error.

### Environment

- Optuna version: 3.1.0 (but happened with 3.0.4 and 3.0.5)
- Python version: 3.8.10
- OS: Linux in Google Colaboratory
- (Optional) Other libraries and their versions:
    - MLFlow: 1.27.0

### Error messages, stack traces, or logs

```shell
This is the error I get:

[I 2023-02-03 14:14:41,177] A new study created in memory with name: my_study
[I 2023-02-03 14:14:41,182] Trial 0 finished with value: 21.34372313649446 and parameters: {'x': -2.619926745793104}. Best is trial 0 with value: 21.34372313649446.
2023/02/03 14:14:41 INFO mlflow.store.db.utils: Creating initial MLflow database tables...
2023/02/03 14:14:41 INFO mlflow.store.db.utils: Updating database tables
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-4-4ed093efaa9c> in <module>
     15 
     16 study = optuna.create_study(study_name="my_study")
---> 17 study.optimize(objective, n_trials=10, callbacks=[mlflc])

23 frames
/usr/local/lib/python3.8/dist-packages/optuna/study/study.py in optimize(self, func, n_trials, timeout, n_jobs, catch, callbacks, gc_after_trial, show_progress_bar)
    423         """
    424 
--> 425         _optimize(
    426             study=self,
    427             func=func,

/usr/local/lib/python3.8/dist-packages/optuna/study/_optimize.py in _optimize(study, func, n_trials, timeout, n_jobs, catch, callbacks, gc_after_trial, show_progress_bar)
     64     try:
     65         if n_jobs == 1:
---> 66             _optimize_sequential(
     67                 study,
     68                 func,

/usr/local/lib/python3.8/dist-packages/optuna/study/_optimize.py in _optimize_sequential(study, func, n_trials, timeout, catch, callbacks, gc_after_trial, reseed_sampler_rng, time_start, progress_bar)
    172         if callbacks is not None:
    173             for callback in callbacks:
--> 174                 callback(study, frozen_trial)
    175 
    176         if progress_bar is not None:

/usr/local/lib/python3.8/dist-packages/optuna/integration/mlflow.py in __call__(self, study, trial)
    146 
    147         with self._lock:
--> 148             self._initialize_experiment(study)
    149 
    150             with mlflow.start_run(

/usr/local/lib/python3.8/dist-packages/optuna/integration/mlflow.py in _initialize_experiment(self, study)
    239 
    240         if self._create_experiment:
--> 241             mlflow.set_experiment(study.study_name)
    242 
    243     def _set_tags(self, trial: optuna.trial.FrozenTrial, study: optuna.study.Study) -> None:

/usr/local/lib/python3.8/dist-packages/mlflow/tracking/fluent.py in set_experiment(experiment_name, experiment_id)
    108         )
    109 
--> 110     client = MlflowClient()
    111     if experiment_id is None:
    112         experiment = client.get_experiment_by_name(experiment_name)

/usr/local/lib/python3.8/dist-packages/mlflow/tracking/client.py in __init__(self, tracking_uri, registry_uri)
     68         final_tracking_uri = utils._resolve_tracking_uri(tracking_uri)
     69         self._registry_uri = registry_utils._resolve_registry_uri(registry_uri, tracking_uri)
---> 70         self._tracking_client = TrackingServiceClient(final_tracking_uri)
     71         # `MlflowClient` also references a `ModelRegistryClient` instance that is provided by the
     72         # `MlflowClient._get_registry_client()` method. This `ModelRegistryClient` is not explicitly

/usr/local/lib/python3.8/dist-packages/mlflow/tracking/_tracking_service/client.py in __init__(self, tracking_uri)
     49         # property method to ensure that the client is serializable, even if the store is not
     50         # self.store  # pylint: disable=pointless-statement
---> 51         self.store
     52 
     53     @property

/usr/local/lib/python3.8/dist-packages/mlflow/tracking/_tracking_service/client.py in store(self)
     53     @property
     54     def store(self):
---> 55         return utils._get_store(self.tracking_uri)
     56 
     57     def get_run(self, run_id):

/usr/local/lib/python3.8/dist-packages/mlflow/tracking/_tracking_service/utils.py in _get_store(store_uri, artifact_uri)
    184 
    185 def _get_store(store_uri=None, artifact_uri=None):
--> 186     return _tracking_store_registry.get_store(store_uri, artifact_uri)
    187 
    188 

/usr/local/lib/python3.8/dist-packages/mlflow/tracking/_tracking_service/registry.py in get_store(self, store_uri, artifact_uri)
     37 
     38         resolved_store_uri = utils._resolve_tracking_uri(store_uri)
---> 39         return self._get_store_with_resolved_uri(resolved_store_uri, artifact_uri)
     40 
     41     @lru_cache(maxsize=100)

/usr/local/lib/python3.8/dist-packages/mlflow/tracking/_tracking_service/registry.py in _get_store_with_resolved_uri(self, resolved_store_uri, artifact_uri)
     47         """
     48         builder = self.get_store_builder(resolved_store_uri)
---> 49         return builder(store_uri=resolved_store_uri, artifact_uri=artifact_uri)

/usr/local/lib/python3.8/dist-packages/mlflow/tracking/_tracking_service/utils.py in _get_sqlalchemy_store(store_uri, artifact_uri)
    146     if artifact_uri is None:
    147         artifact_uri = DEFAULT_LOCAL_FILE_AND_ARTIFACT_PATH
--> 148     return SqlAlchemyStore(store_uri, artifact_uri)
    149 
    150 

/usr/local/lib/python3.8/dist-packages/mlflow/store/tracking/sqlalchemy_store.py in __init__(self, db_uri, default_artifact_root)
    137         inspected_tables = set(sqlalchemy.inspect(self.engine).get_table_names())
    138         if any(table not in inspected_tables for table in expected_tables):
--> 139             mlflow.store.db.utils._initialize_tables(self.engine)
    140         Base.metadata.bind = self.engine
    141         SessionMaker = sqlalchemy.orm.sessionmaker(bind=self.engine)

/usr/local/lib/python3.8/dist-packages/mlflow/store/db/utils.py in _initialize_tables(engine)
     30     _logger.info("Creating initial MLflow database tables...")
     31     InitialBase.metadata.create_all(engine)
---> 32     _upgrade_db(engine)
     33 
     34 

/usr/local/lib/python3.8/dist-packages/mlflow/store/db/utils.py in _upgrade_db(engine)
    146     with engine.begin() as connection:
    147         config.attributes["connection"] = connection  # pylint: disable=E1137
--> 148         command.upgrade(config, "heads")
    149 
    150 

/usr/local/lib/python3.8/dist-packages/alembic/command.py in upgrade(config, revision, sql, tag)
    376         tag=tag,
    377     ):
--> 378         script.run_env()
    379 
    380 

/usr/local/lib/python3.8/dist-packages/alembic/script/base.py in run_env(self)
    567 
    568         """
--> 569         util.load_python_file(self.dir, "env.py")
    570 
    571     @property

/usr/local/lib/python3.8/dist-packages/alembic/util/pyfiles.py in load_python_file(dir_, filename)
     92     if ext == ".py":
     93         if os.path.exists(path):
---> 94             module = load_module_py(module_id, path)
     95         else:
     96             pyc_path = pyc_file_from_path(path)

/usr/local/lib/python3.8/dist-packages/alembic/util/pyfiles.py in load_module_py(module_id, path)
    108     assert spec
    109     module = importlib.util.module_from_spec(spec)
--> 110     spec.loader.exec_module(module)  # type: ignore
    111     return module

/usr/lib/python3.8/importlib/_bootstrap_external.py in exec_module(self, module)

/usr/lib/python3.8/importlib/_bootstrap.py in _call_with_frames_removed(f, *args, **kwds)

/usr/local/lib/python3.8/dist-packages/mlflow/store/db_migrations/env.py in <module>
     82     run_migrations_offline()
     83 else:
---> 84     run_migrations_online()

/usr/local/lib/python3.8/dist-packages/mlflow/store/db_migrations/env.py in run_migrations_online()
     70         )
     71 
---> 72     with connectable.connect() as connection:
     73         context.configure(
     74             connection=connection, target_metadata=target_metadata, render_as_batch=True

AttributeError: 'Connection' object has no attribute 'connect'
```
```


### Steps to reproduce

1. Open new Notebook in Google Colab.
2. Install Optuna and MLFlow in one block of code.
```python
!pip install -q optuna==3.1.0 
!pip install -q mlflow==1.27.0
```
3. Run the example found in [`optuna.integration.MLflowCallback`](https://optuna.readthedocs.io/en/stable/reference/generated/optuna.integration.MLflowCallback.html)
```python
import mlflow
import optuna
from optuna.integration.mlflow import MLflowCallback

mlflow.set_tracking_uri("sqlite:///mydb1.sqlite")

def objective(trial):
    x = trial.suggest_float("x", -10, 10)
    return (x - 2) ** 2

mlflc = MLflowCallback(
    tracking_uri=mlflow.get_tracking_uri(),
    metric_name="my metric score",
)

study = optuna.create_study(study_name="my_study")
study.optimize(objective, n_trials=10, callbacks=[mlflc])
```
4. Then I get the error message.

**Comment by nzw0301** [comment] 2023-02-03 17:49
Thank you for reporting it. 

Maybe mlflow version is a little bit old. When I import the following versions (and restart notebook), the shared code works.

```ipython
!pip install -U optuna==3.1.0
!pip install -U mlflow==2.1.1
!pip install -U "SQLAlchemy<2.0"
```

**Comment by nzw0301** [comment] 2023-02-06 10:58
Let me close this issue since my previous comment gave the working case and was not a bug. Please feel free to reopen this PR if there is still an issue on colab.

**Closed by nzw0301** 2023-02-06 10:58 UTC
Labels: bug
