### ISSUE TITLE
unrobust optuna sampling behaviour

### ISSUE THREAD

**Issue by HarveyYan** [optuna/optuna#3982] opened 2022-09-09 22:15 UTC
### Expected behavior

I have something like this in the code: `trial.suggest_categorical('somename', [False, True])`

and when it is running sometimes it gives an error like `ValueError: 'True' not in (False, True).`, but sometimes it samples just fine without this kind of error.

I looked into issue with pdb and at `optuna/samplers/nsgaii/_crossover.py(115)` you actually have a `child_params` dictionary which contains  sampled parameters and there is `{..., 'somename': "False"}`, although it would make much better sense to have that parameter sampled in `boolean` values.

Any ideas why that would be happening? Thank you in advance.

### Environment

- Optuna version: 3.0.1
- Python version: 3.8.13
- OS:Linux-4.15.0-1051-aws-x86_64-with-glibc2.17
- (Optional) Other libraries and their versions:

### Error messages, stack traces, or logs

```shell
File "/lib/python3.8/site-packages/optuna/study/study.py", line 419, in optimize
    _optimize(
  File "/lib/python3.8/site-packages/optuna/study/_optimize.py", line 66, in _optimize
    _optimize_sequential(
  File "/lib/python3.8/site-packages/optuna/study/_optimize.py", line 160, in _optimize_sequential
    frozen_trial = _run_trial(study, func, catch)
  File "/lib/python3.8/site-packages/optuna/study/_optimize.py", line 187, in _run_trial
    trial = study.ask()
  File "/lib/python3.8/site-packages/optuna/study/study.py", line 514, in ask
    trial = trial_module.Trial(self, trial_id)
  File "/lib/python3.8/site-packages/optuna/trial/_trial.py", line 54, in __init__
    self._init_relative_params()
  File "/lib/python3.8/site-packages/optuna/trial/_trial.py", line 63, in _init_relative_params
    self.relative_params = self.study.sampler.sample_relative(
  File "/lib/python3.8/site-packages/optuna/samplers/nsgaii/_sampler.py", line 211, in sample_relative
    child_params = perform_crossover(
  File "/lib/python3.8/site-packages/optuna/samplers/nsgaii/_crossover.py", line 115, in perform_crossover
    if _is_contained(child_params, search_space):
  File "/lib/python3.8/site-packages/optuna/samplers/nsgaii/_crossover.py", line 160, in _is_contained
    if not param_distribution._contains(param_distribution.to_internal_repr(param)):
  File "/lib/python3.8/site-packages/optuna/distributions.py", line 516, in to_internal_repr
    raise ValueError(f"'{param_value_in_external_repr}' not in {self.choices}.")
ValueError: 'True' not in (False, True).
```

### Steps to reproduce

1.
2.
3.
```python
# python code
```

**Comment by nzw0301** [comment] 2022-09-10 02:57
Hi, could you share the minimal reproducible code?

**Comment by nzw0301** [comment] 2022-09-10 14:44
I couldn't see any error when I ran the following code:

```python
import optuna

def objective1(trial):
    for i in range(10):
        trial.suggest_categorical(f"x_{i}", [False, True])
    return trial.suggest_float("y", 0, 1)


for seed in range(100):
    study = optuna.create_study(sampler=optuna.samplers.NSGAIISampler(seed=seed))
    study.optimize(objective1, n_trials=30)

```

**Comment by skotaro** [comment] 2022-09-30 06:32
I encountered the same issue as well with version 3.0.1. 

The bug seems to be deterministic. Conditions are
- Trial has string and non-string categorical parameters.
- n_trials > population_size (i.e. when child parameters are generated)

Here is minimum reproducible code.

```python
import optuna
from random import random

def objective1(trial):
    # This doesn't fail
    # cat_1 = trial.suggest_categorical(f"cat_1", [10, 12]) 
    # cat_2 = trial.suggest_categorical(f"cat_2", [1, 2, 3])

    # This doesn't fail
    # cat_1 = trial.suggest_categorical(f"cat_1", ['para1', 'para2']) 
    # cat_2 = trial.suggest_categorical(f"cat_2", ['1', '2', '3'])

    # This doesn't fail
    # cat_1 = trial.suggest_categorical(f"cat_1", [True, False])
    # cat_2 = trial.suggest_categorical(f"cat_2", [1, 2, 3])

    # This fails
    cat_1 = trial.suggest_categorical(f"cat_1", ['string1', 'string2'])
    cat_2 = trial.suggest_categorical(f"cat_2", [1, 2, 3])

    # This fails
    # cat_1 = trial.suggest_categorical(f"cat_1", ['string1', 'string2'])
    # cat_2 = trial.suggest_categorical(f"cat_2", [True, False])

    return random()

population_size = 50

study = optuna.create_study(sampler=optuna.samplers.NSGAIISampler(population_size=population_size))

study.optimize(objective1, n_trials=population_size-1) # This doesn't fail
study.optimize(objective1, n_trials=population_size+1) # This fails if trial has string and non-string categorical parameters

```

**Comment by nzw0301** [comment] 2022-09-30 07:05
@skotaro Brilliant. Thank you for sharing the minimal code to get the error.

**Comment by not522** [comment] 2022-09-30 07:11
Thank you for sharing the code! I found a bug here. We should specify `dtype=object` to prevent unexpected casting.
https://github.com/optuna/optuna/blob/a7cd842f2aca675e517fc7bf74f22762380aeb24/optuna/samplers/nsgaii/_crossover.py#L40-L45

**Comment by not522** [comment] 2022-10-07 08:33
The bug has been fixed. I will close this issue after adding a test.

**Closed** 2023-03-13 06:18 UTC
Labels: bug
