### ISSUE TITLE
ZeroDivisionError: when migrating schema from v2.6.0.a to v3.0.0.a

### ISSUE THREAD

**Issue by jaak-s** [optuna/optuna#4216] opened 2022-11-30 21:25 UTC
### Expected behavior

Upgrade to complete.

### Environment

- Optuna version: 3.0.3
- Python version: 3.8.7
- OS: Windows (also similar error in Linux)
- (Optional) Other libraries and their versions:

### Error messages, stack traces, or logs

```shell
File "...\lib\site-packages\optuna\distributions.py", line 680, in _adjust_int_uniform_high
  if r % step != 0:
ZeroDivisionError: integer division or modulo by zero
```
```


### Steps to reproduce

1. Install old optuna
2. Run studies with PostgreSQL backend with step=0 (somehow, not clear how I got these runs)
3. Install optuna 3.0.3
4. Upgrade schema.


### Additional context (optional)

I have a lot of Optuna studies in psql created by old Optuna versions. Some probably have step==0 (not sure how) and when upgrading we get division by zero error. Maybe the step is 0 when low and high are set to equal.

**Comment by nzw0301** [comment] 2022-12-01 03:11
Hi, could you share minimal reproducible codes with us?

**Comment by nzw0301** [comment] 2023-01-31 16:57
Since we've not seen any update for a while, let me close this once. Please feel free to re-open with additional info.

**Closed by nzw0301** 2023-01-31 16:57 UTC
Labels: bug
