### ISSUE TITLE
How to Initialize the start point of a sample(or study)?

### ISSUE THREAD

**Issue by yhhu99** [optuna/optuna#3387] opened 2022-03-16 10:28 UTC
### Environment

- Optuna version:
- Python version:
- OS:
- (Optional) Other libraries and their versions:

### Description

I wonder if there exists a method for user to initialize a start point for the sampler(or study), so that it would converge faster?
For example , if I can set a good population for the NSGAII sampler as a initial population, it can converge very fast and get a good result.

### Error messages, stack traces, or logs

```shell
no messages, just a question
```

### Steps to reproduce

1.
2.
3.
```python
# python code
```

**Comment by himkt** [comment] 2022-03-16 10:44
Duplicate of #3388

**Closed by himkt** 2022-03-16 10:44 UTC
Labels: question
