### ISSUE TITLE
The "storage" parameter of optuna.study.create_study

### ISSUE THREAD

**Issue by Yovoss** [optuna/optuna#3384] opened 2022-03-15 15:00 UTC
### Environment

- Optuna version:
- Python version:
- OS:
- (Optional) Other libraries and their versions:

### Description

 when i read the storage description in the API reference of optuna.study.create_study, there is a sentence, just like "If this argument is set to None, in-memory storage is used, and the [Study] will not be persistent."
How to understand "the [Study] will not be persistent"???
when the OOM occurred, the study will stop? or something else will happen?

### Error messages, stack traces, or logs

```shell
no others
```

### Steps to reproduce

1.
2.
3.
```python
# python code
```

**Comment by himkt** [comment] 2022-03-15 23:24
Unlike other persistent storages such as `RDBStorage` and `RedisStorage`, `InMemoryStorage` (default in-memory storage of Optuna) doesn't store data to some persistent storage. You can only access your study in a process and data will not be available after a process is stopped.

> when the OOM occurred, the study will stop? or something else will happen?

Study will stop. Whether the interpreter can be restored on try-catch to access study depends on the situation. If your objective likely fails on errors, I recommend to use persistent storages like RDBStorage.

**Comment by Yovoss** [comment] 2022-03-16 03:30
@himkt 
Thanks ! And if i use the InMemoryStorage, the method like "study.best_trial" will still work or not ? Or just the tables and informations originally in RDBStorage can not be available ?
If i adopted the InMemoryStorage, will the speed of tuning process increase? 
Besides, when i use optuna to tune the hyperparameter of deep learning model in linux with 160 G memory, the memory usage increases gradually until the OOM. And the optuna document suggest set gc_after_trial = True to solve the problem, but i find that is useless.
So i want to know if there are some clear  inside mechanism and solutions?
Thank you a lot !

**Comment by himkt** [comment] 2022-03-16 04:11
> Thanks ! And if i use the InMemoryStorage, the method like "study.best_trial" will still work or not ? 

It works. After finishing the program, you cannot access the study object (because it is a Python object).

> If i adopted the InMemoryStorage, will the speed of tuning process increase?

Yes. an in-memory storage is faster than other persistent storages.

> Besides, when i use optuna to tune the hyperparameter of deep learning model in linux with 160 G memory, the memory usage increases gradually until the OOM. And the optuna document suggest set gc_after_trial = True to solve the problem, but i find that is useless.

We cannot investigate without some reproducible code. OOM typically causes with third-party libraries. Please try some techniques that libraries provide to avoid memory leak. (e.g. https://github.com/optuna/optuna/issues/1178)

**Comment by Yovoss** [comment] 2022-03-16 05:15
thank you, i will have more tries on this problems, and if there are still questions, i will provide some codes and error messages.
Thank you again!

**Comment by Yovoss** [comment] 2022-03-20 10:53
@himkt I run  the script to tune the hyperparameter of GRU model, train on 2555 samples, validate on 318 samples and set the n_trials=100. And after about 20 hours, the memory of linux server  has been run out. Then the process were killed by the system. When i check the postgresql db table "trials", i can see that it has been optimized to trial 75. Although the process has been killed, the "state" of trial 75 is still RUNNING.
![image](https://user-images.githubusercontent.com/30063890/159158746-2ab54f65-55ee-408f-ad84-8e3b732be60f.png)
So, i want to know if i restart the study, and set the parameter "load_if_exists=True" to continue the optimization，whether the "RUNNNG" state of trial 75 will influence the new process or not?
Thank you!

**Comment by Yovoss** [comment] 2022-03-20 11:00
@himkt There is another question about the OOM, you have told me to reference the #1178 post to solve the OOM, but i fine there is no much difference when i set tf.keras.backend.clear_session,my code is below.
![image](https://user-images.githubusercontent.com/30063890/159159087-232ea292-7edd-454a-a010-1ddd60c23b9f.png)
![1647773958(1)](https://user-images.githubusercontent.com/30063890/159159101-bc622ad5-f7a9-44bc-a16a-ecd35516322e.png)
![1647774015(1)](https://user-images.githubusercontent.com/30063890/159159131-afb0df15-9725-452f-9312-3d1cf62ff499.png)
so i want to know if there are some errors in code? Thank you

**Comment by himkt** [comment] 2022-03-20 15:49
> So, i want to know if i restart the study, and set the parameter "load_if_exists=True" to continue the optimization，whether the "RUNNNG" state of trial 75 will influence the new process or not?

Running trials will be left until you explicitly fail them, but, it doesn't influence the optimization. When you resume the optimization, trial 76, 77, ... will be created.

> There is another question about the OOM

In generally speaking, I think you shouldn't to store model on instance variable since it may hold GPU memory even after training. You can restore the model after optimization by storing serialization path (str) of the best model. I think OOM is not related to Optuna.

**Comment by Yovoss** [comment] 2022-03-21 04:43
> 
@himkt Yes! the zombie study will not influence the resumed optimization!
And after more tries on the OOM question, the K.clear_session() did work out the OOM problem. But there is another error occurred.
I have wrote a CALLBACK function in class Objective() to get the best model after all trials, and save the best model into .h5 file and  then use the best model to predict samples in validation dataset. But when the study finished, there is error about the predict() function.
So i want to know if K.clear_session() leads to this error? and is there some solutions?
![image](https://user-images.githubusercontent.com/30063890/159206371-cd6f8cb6-c0a5-4a59-b791-dccfd20aaa7e.png)
![1647837767(1)](https://user-images.githubusercontent.com/30063890/159206433-fdc5dca6-b8a6-4d8f-abb1-0c5b61dff751.png)
![image](https://user-images.githubusercontent.com/30063890/159206464-5c2f2ad7-9c01-49d7-ba33-f38b15dd7a0c.png)

**Comment by himkt** [comment] 2022-03-22 02:31
> after more tries on the OOM question, the K.clear_session() did work out the OOM problem

I'm sorry to hear that. I have no idea for now.

> I have wrote a CALLBACK function in class Objective() to get the best model after all trials, and save the best model into .h5 file and then use the best model to predict samples in validation dataset

Let me say again but I think it shouldn't store a model in an instance variable.

> how to restore the baest model by storing serialization path?

I'm not familiar with keras but I think you can load a model weights 
 using https://www.tensorflow.org/guide/keras/save_and_serialize.

```python
def objective(trial) -> float:
    # hyperparameters
    model = build_model(trial)

    # training
    model.fit(...)

    # save
    mode.save(f"path/to/serialization_{trial.number}")  # store the model on a storage.

    # returning a score
    return model.evaluate(...)[0]


...
study.optimize(objective)  # run optimization

# restore the best model and predict on
best_trial = study.best_trial
model = keras.models.load_model(f"path/to/serialization_{best_trial.number}")
model.predict(X_validation)
```

**Comment by himkt** [comment] 2022-03-22 02:33
Let me close this issue as I believe I answered the original question ("the storage parameter of create_study"). Please also read keras documentation for saving/loading a keras model since I'm not familiar with keras. :pray:

**Closed by himkt** 2022-03-22 02:33 UTC
Labels: question
