### ISSUE TITLE
No module named 'optuna_custom_visualization'

### ISSUE THREAD

**Issue by manza-ari** [optuna/optuna#3334] opened 2022-02-25 06:52 UTC
### Expected behavior

Optuna is working fine on my desktop when I copy my virtual environment on a remote server it gives me the following error. Any recommendations? 
![Screenshot from 2022-02-25 15-48-38](https://user-images.githubusercontent.com/33715985/155668514-cb0ad17d-f85a-415d-97af-232a032363d9.png)
 

### Environment

- Optuna version:
- Python version:
- OS:
- (Optional) Other libraries and their versions:

### Error messages, stack traces, or logs

```shell
ModuleNotFoundError: No module named 'optuna_custom_visualization'
```

### Steps to reproduce

1.
2.
3.
```python
# python code
```

**Comment by himkt** [comment] 2022-02-25 08:17
@manza-ari I'm afraid but I think it is not related to Optuna but is the Python question. If `optuna_custom_visualization` is a Python file, make sure `optuna_custom_visualization.py` is located on the current directory. If it is a module, make sure if it is correctly installed.

**Comment by manza-ari** [comment] 2022-02-25 08:27
oh, I am sorry for not getting some relevant results for this error.

**Comment by himkt** [comment] 2022-02-25 15:23
> I thought it is Optuna's

You mean you think this error happens by Optuna, right? If so, I'll investigate if you share me a minimum reproducing code.

**Comment by nzw0301** [comment] 2022-02-27 02:04
> oh, I am sorry for not getting some relevant results for this error. I thought it is Optuna's

It sounds the root cause might not come from optuna. Let me close this issue once. If the issue comes from Optuna or there is a question on this PR, please feel free to reopen this with (minimal) reproducible codes.  As @himkt said, we'll really appreciate you for sharing minimal reproducible codes when an issue is created to investigate the issue smoothly.

**Closed by nzw0301** 2022-02-27 02:04 UTC
Labels: question
